### DISCUSSION TITLE
New lint rule: token value defaults

### DISCUSSION THREAD

**Discussion by bennypowers** [RedHat-UX/red-hat-design-tokens#52] [Ideas]
Proposed lint rule would either require, disallow, or permit either tokens to be used with defaults.

## Why?

Component (shadow) CSS should generally be expected to contain defaults, as the component's page context is unknown, whereas global page css should generally not use defaults, as it can be assumed that the global tokens sheet is loaded.

This rule would allow configuring per file which style to adopt:

```yaml
# .stylelintrc.yml
overrides:
  - files:
      - docs/**/*.scss
    rules:
      rhds/token-defaults: forbidden
  - files:
      - elements/**/*.css
    rules:
      rhds/token-defaults: required
```

## Options

`defaults`: `required|forbidden|either`

:x: The following CSS would ERROR for `defaults: "required"`

```css
color: var(--rh-color-red-500);
```

:heavy_check_mark: The following CSS would be ALLOWED for `defaults: "required"`

```css
color: var(--rh-color-red-500, #ee0000);
```

:x: The following CSS would ERROR for `defaults: "forbidden"`

```css
color: var(--rh-color-red-500, #ee0000);
```

:heavy_check_mark: The following CSS would be ALLOWED for `defaults: "forbidden"`

```css
color: var(--rh-color-red-500);
```

:heavy_check_mark: The following CSS would be ALLOWED for `defaults: "either"`

```css
color: var(--rh-color-red-500);
```
```css
color: var(--rh-color-red-500, #ee0000);
```
