### ISSUE TITLE
bug: provider tokens and elements that don't set a default `color-palette`

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-tokens#147]
As of last release we generate  a`color-context-provider.css` file with the following contents:  

```css
:host([color-palette^="dark"]) { --context: dark; }
:host([color-palette^="light"]) { --context: light; }

:host([color-palette="lightest"]) {
  --rh-color-surface: var(--rh-color-surface-lightest, #ffffff);
}
:host([color-palette="lighter"]) {
  --rh-color-surface: var(--rh-color-surface-lighter, #f2f2f2);
}
:host([color-palette="light"]) {
  --rh-color-surface: var(--rh-color-surface-light, #e0e0e0);
}
:host([color-palette="dark"]) {
  --rh-color-surface: var(--rh-color-surface-dark, #383838);
}
:host([color-palette="darker"]) {
  --rh-color-surface: var(--rh-color-surface-darker, #1f1f1f);
}
:host([color-palette="darkest"]) {
  --rh-color-surface: var(--rh-color-surface-darkest, #151515);
}
```

These styles are included with components that are a color context provider.  However some components do not default to setting their `color-palette` attribute, so `--rh-color-surface` does not get set in the above rule sets leaving that style undefined.  Such an element is `rh-tile` [as reported by Michael Wells](https://redhat-internal.slack.com/archives/C0686DG8YSJ/p1729264660882679).  

I think we have 1 of 2 fixes.  

In this repo:

```css
:host(:not([color-palette])),
:host([color-palette="lightest"]) {
  --rh-color-surface: var(--rh-color-surface-lightest, #ffffff);
}
```

Or in RHDS every component that is a provider must specify and reflect a `color-palette` attribute by default.

Thoughts @bennypowers @markcaron
