### ISSUE TITLE
[bug] font-family stack not referencing correct font

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-tokens#17]
The font-family stacks are referencing non-spaced versions of the fonts.

"RedHatDisplay"', '"RedHatText"', "RedHatMono"'

As discussed in standup there is a difference between what PatternFly and RHDS would reference.  

Should this reference be the following instead?

"Red Hat Display"', '"Red Hat Text"', "Red Hat Mono"'

https://github.com/RedHat-UX/red-hat-design-tokens/blob/80f172e7479507d7fa64bebf831259976de42d27/tokens/font/family.yml#L12-L48

**Comment by coreyvickery** [comment]
@zeroedin Is it okay to use both? I pulled this from redhat.com.

`font-family: RedHatDisplay,"Red Hat Display",Overpass,Overpass,"Helvetica Neue",Arial,sans-serif;`

**Comment by bennypowers** [comment]
I had an issue with rh-footer not respecting Hebrew fonts. This was the solution I prepared:

```css
--rh-font-family-heading: RedHatDisplay "Red Hat Display", "Noto Sans Hebrew", Overpass, Helvetica, Arial, sans-serif;
--rh-font-family-body-text: RedHatText, "Red Hat Text", "Noto Sans Hebrew", Overpass, Helvetica, Arial, sans-serif;
--rh-font-family-code: RedHatMono, "Red Hat Mono", "Courier New", Courier, monospace;
```

Since `Noto Sans Hebrew` only has Hebrew glyphs it should just transparently slot into the font stack

![image](https://user-images.githubusercontent.com/1466420/185103304-717f40f6-6525-48e1-872e-b5cf936a0eb3.png)

It might be worth our while to pile all those specific glyphsets on to the design system, so as to provide reasonable defaults for any situation. The downside to that approach would be extra bytes over the wire. We could alternatively recommend that users with specific i18n needs set the `--rh-font-family-*` variables themselves.

**Comment by markcaron** [comment]
Could we not use the `[lang]` attribute in our base CSS to pass in the proper Noto Sans font stack?

```css
[lang="he"] {
    --rh-font-family-heading: RedHatDisplay "Red Hat Display", "Noto Sans Hebrew", Overpass, Helvetica, Arial, sans-serif;
    --rh-font-family-body-text: RedHatText, "Red Hat Text", "Noto Sans Hebrew", Overpass, Helvetica, Arial, sans-serif;
}
```
