### ISSUE TITLE
New Lint Rule: Unknown `--rh` token

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-tokens#64]
#1 Provides an opportunity to add a linting rule for unknown tokens

say we deleted the tokens `--rh-color-black-*` and added `--rh-color-gray-*`

in that case, this stylesheet should fail this rule:

```css
#icon {
  color: var(--rh-color-black-900, #151515);
}
```

we could provide an `migrations` options which would allow us to auto-fix these errors:

```yaml
rhds/unknown-token:
  - true
  - migrations:
    --rh-color-black-400: --rh-color-grey-300
```
