### ISSUE TITLE
New Lint Rule: no unnammed token value

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-tokens#67]
fails:
```css
a {
  color: #ee0000;
}
```

passes:
```css
a {
  color: var(--rh-color-accent-brand-on-light, #ee0000);
}
```
